In [2]:
import requests
import csv
import time

url = "https://random-data-api.com/api/users/random_user"

with open("users.csv", mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["id", "FirstName", "LastName", "Username", "Email", "Avatar", "Gender", "DoB", "Address"])
    for i in range(10):
        response = requests.get(url).json()
        writer.writerow([response["id"], response["first_name"], response["last_name"], response["username"], response["email"], response["avatar"], response["gender"], response["date_of_birth"], response["address"]])
        time.sleep(1)

In [5]:
import pandas as pd
df = pd.read_csv("users.csv")
df.head(10)

,id,FirstName,LastName,Username,Email,Avatar,Gender,DoB,Address
0,3534,Sulema,Von,sulema.von,sulema.von@email.com,https://robohash.org/sintquibusdamvoluptas.png...,Female,2004-10-27,"{'city': 'Lake Franklyn', 'street_name': 'Welc..."
1,9229,Thomasina,Crona,thomasina.crona,thomasina.crona@email.com,https://robohash.org/cupiditatenihilsequi.png?...,Bigender,1997-09-30,"{'city': 'Padbergmouth', 'street_name': ""O'Kee..."
2,3891,Tamica,Anderson,tamica.anderson,tamica.anderson@email.com,https://robohash.org/etsedest.png?size=300x300...,Agender,1978-06-29,"{'city': 'Schmittmouth', 'street_name': 'Rubin..."
3,1326,Pat,Brakus,pat.brakus,pat.brakus@email.com,https://robohash.org/quasinumquammodi.png?size...,Agender,1989-01-26,"{'city': 'Tonyatown', 'street_name': 'Dario Ma..."
4,9399,Royal,Walker,royal.walker,royal.walker@email.com,https://robohash.org/inarchitectoaut.png?size=...,Agender,1986-06-07,"{'city': 'North Craig', 'street_name': 'Herzog..."
5,8583,Wyatt,Wuckert,wyatt.wuckert,wyatt.wuckert@email.com,https://robohash.org/voluptatumquirem.png?size...,Polygender,1983-12-09,"{'city': 'Gerlachport', 'street_name': 'Hauck ..."
6,186,Augusta,Senger,augusta.senger,augusta.senger@email.com,https://robohash.org/quidoloresvelit.png?size=...,Male,1972-08-20,"{'city': 'Port Aniballand', 'street_name': 'Fr..."
7,7061,Laverne,Yundt,laverne.yundt,laverne.yundt@email.com,https://robohash.org/omnisuttempora.png?size=3...,Agender,1997-02-04,"{'city': 'Mrazborough', 'street_name': 'Grant ..."
8,5873,Jarrod,Bernhard,jarrod.bernhard,jarrod.bernhard@email.com,https://robohash.org/numquamculpavitae.png?siz...,Agender,1971-12-07,"{'city': 'Hongfort', 'street_name': 'Errol Wal..."
9,4694,Domingo,Schultz,domingo.schultz,domingo.schultz@email.com,https://robohash.org/placeatesseomnis.png?size...,Female,2003-07-23,"{'city': 'Rileyside', 'street_name': 'Sol Moun..."

In [3]:
import csv
import datetime

with open("users.csv", mode="r") as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    for row in reader:
        dob = datetime.date.fromisoformat(row[7])
        age = datetime.date.today().year - dob.year
        print(f"{row[1]} {row[2]} is {age} years old.")

Sulema Von is 19 years old.
Thomasina Crona is 26 years old.
Tamica Anderson is 45 years old.
Pat Brakus is 34 years old.
Royal Walker is 37 years old.
Wyatt Wuckert is 40 years old.
Augusta Senger is 51 years old.
Laverne Yundt is 26 years old.
Jarrod Bernhard is 52 years old.
Domingo Schultz is 20 years old.

In [6]:
import csv
import datetime

with open("users.csv", mode="r") as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    user_input = input("Enter ID or username of user: ")
    for row in reader:
        if row[0] == user_input or row[3] == user_input:
            dob = datetime.date.fromisoformat(row[7])
            age = datetime.date.today().year - dob.year
            print(f"ID: {row[0]}\nFirst Name: {row[1]}\nLast Name: {row[2]}\nUsername: {row[3]}\nEmail: {row[4]}\nAvatar: {row[5]}\nGender: {row[6]}\nDate of Birth: {row[7]}\nAddress: {row[8]}\nAge: {age}")
            break
    else:
        print("User not found.")

Enter ID or username of user: 3534
ID: 3534
First Name: Sulema
Last Name: Von
Username: sulema.von
Email: sulema.von@email.com
Avatar: https://robohash.org/sintquibusdamvoluptas.png?size=300x300&set=set1
Gender: Female
Date of Birth: 2004-10-27
Address: {'city': 'Lake Franklyn', 'street_name': 'Welch Mountain', 'street_address': '313 Schiller Burgs', 'zip_code': '38409-9509', 'state': 'New Jersey', 'country': 'United States', 'coordinates': {'lat': -19.106366749444305, 'lng': -95.70945767287164}}
Age: 19